# Service Information
service:
  name: @project.name@
  description: @project.description@
  version: @project.version@

# Spring
spring:
  application:
    name: @project.name@

# WebServer
server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    whitelabel:
      enabled: false

# Tracing
opentracing:
  spring:
    web:
      client:
        enabled: false
    cloud:
      async:
        enabled: false
  jaeger:
    enabled: true
    log-spans: true
    expand-exception-logs: true
    enable-b3-propagation: true
    # Sampling - Constant
    probabilistic-sampler:
      sampling-rate: 1.0
    # Sampling - RateLimited
    rate-limiting-sampler:
      max-traces-per-second: 3
    # Endpoint
    http-sender:
      url: http://localhost:14268/api/traces
    #udp-sender:
    #  host: localhost
    #  port: 6831

# Error Reporting
#sentry:
#  dsn: http://localhost:9109

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  metrics:
    distribution:
      sla:
        http:
          server:
            requests: 10ms, 25ms, 50ms, 100ms, 500ms, 1s, 5s
    export:
      prometheus:
        enabled: true

# Logging
logging:
  pattern:
    console: "%d %highlight(%-5level) %logger : %msg%n"
    file: "%d %-5level %logger : %msg%n"
  level:
    root: WARN
    org.springframework: INFO
    service: TRACE
    # io.opentracing: TRACE
